### ISSUE TITLE
编译出的文件并入安装包进世界闪退

### ISSUE THREAD

**Issue by Frog54977402** [ddf8196/MaterialBinTool#15]
编译目标是1.20.44解出的东西，用的工具是0.9.1版本，但用的shaderc.exe是旧版的（因为不知道怎么搞适用于新版的），不明白闪退跟这个有没有关系

**Comment by Arctrometa** [comment]
is the issue still persisting after using the newest `shaderc.exe`?

**Comment by Frog54977402** [comment]
> is the issue still persisting after using the newest `shaderc.exe`?

I don't know where can I get the newest shaderc.exe file

**Comment by veka0** [comment]
Currently, most up-to-date versions can be found here https://github.com/veka0/bgfx-mcbe/releases/tag/binaries
I opened a PR to the original bgfx-mcbe repository but it was never merged.

**Comment by Frog54977402** [comment]
> Currently, most up-to-date versions can be found here https://github.com/veka0/bgfx-mcbe/releases/tag/binaries I opened a PR to the original bgfx-mcbe repository but it was never merged.

Thank you,it really works
