### ISSUE TITLE
shaderc.exe is not detected in the Termux application

### ISSUE THREAD

**Issue by ahmaf-gif** [ddf8196/MaterialBinTool#8]
I followed the Compile steps.

java -jar mtb. jar -s shaderc.exe -c RenderChunk

And the result is "shaderc not found"

**Comment by ddf8196** [comment]
The shaderc.exe included in the Release only supports Windows x64, not Android. To use it on Android, you can compile shaderc from source code by yourself.

**Comment by ahmaf-gif** [comment]
Can you show an example or a tutorial?
